server:
  port: 8302

spring:
  #rabbitmq 设置
  rabbitmq:
    host: 47.98.253.2
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      trace:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
####  我的github配置和此处一样，这里只是作为参考作用。
data:
  env: NaN
  user:
    username: NaN
    password: NaN
## 开启消息跟踪
