###服务启动端口号
server:
  port: 1082
###服务名称(服务注册到eureka名称)
spring:
  application:
    name: rabbit
  # 支持发布确认
  rabbitmq:
    publisher-confirms: false

###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7080/eureka

  # 检测与续约时间
instance:
  #   Eureka客户端向服务端发送心跳的时间间隔，单位为秒
  lease-renewal-interval-in-seconds: 1
  #   服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则踢出
  lease-expiration-duration-in-seconds: 2
#rabbitmq 配置
rq:
  rabbitmq:
    host: 47.98.253.2
    port: 5672
    username: guest
    password: guest

