###服务启动端口号
server:
  port: 1082
###服务名称(服务注册到eureka名称)
spring:
  application:
    name: rabbit
  # 支持发布确认
  rabbitmq:
    #主机连接信息
    host: 47.98.253.2
    port: 5672
    username: guest
    password: guest
    # publisher-confirm-type: correlated #  （新版本写法作用与 publisher-confirms: true  一致）
    publisher-confirms: true #消息发送到交换机确认机制，是否确认回调
    publisher-returns: true  #支持消息发送失败返回队列

    #配置监听
    listener:
      simple:
        acknowledge-mode: manual #设置消费端手动 ack   none不确认  auto自动确认  manual手动确认
        concurrency: 1   #消费者最小数量
        max-concurrency: 1 #消费之最大数量
        #开启消费者重试机制(为false时关闭消费者重试，这时消费端代码异常会一直重复收到消息)
        retry:
          enabled: true
          max-attempts: 5 #重试次数5
          initial-interval: 5000  #重试时间间隔
        #重试次数超过上面的设置之后是否丢弃（false不丢弃时需要写相应代码将该消息加入死信队列）
        default-requeue-rejected: true
        #在单个请求中处理的消息个数，他应该大于等于事务数量(unack的最大数量)
        prefetch: 2


###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7080/eureka

  # 检测与续约时间
instance:
  #   Eureka客户端向服务端发送心跳的时间间隔，单位为秒
  lease-renewal-interval-in-seconds: 1
  #   服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则踢出
  lease-expiration-duration-in-seconds: 2
#rabbitmq 配置
rq:
  rabbitmq:
    host: 47.98.253.2
    port: 5672
    username: guest
    password: guest

