server:
  port: 8012

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/master?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 123456

  jackson:
    #参数意义：
    #JsonInclude.Include.ALWAYS       默认
    #JsonInclude.Include.NON_DEFAULT   属性为默认值不序列化
    #JsonInclude.Include.NON_EMPTY     属性为 空（””） 或者为 NULL 都不序列化
    #JsonInclude.Include.NON_NULL      属性为NULL  不序列化
    default-property-inclusion: ALWAYS
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  # 设置静态资源或者动态资源访问地址,可以随便起名字，但是同时只能有一个存在

  #静态资源
  resources:
    static-locations: classpath:/resources/
  #动态资源
    # 设置thymeleaf路径默认为src/main/resources/templates/web/
    # 切记要带 最后要带 /
  thymeleaf:
    prefix: classpath:/templates/web/
    suffix: .html
    cache: false
  mvc:
    static-path-pattern: /**
