server:
  port: 5083
spring:
  application:
    name: myabtis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7080/eureka
instance:
  lease-renewal-interval-in-seconds: 1
  lease-expiration-duration-in-seconds: 2
